[package]
name = "min-max-heap"
version = "0.1.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
description = "A double-ended priority queue"
repository = "https://github.com/tov/min-max-heap-rs"
homepage = "https://github.com/tov/min-max-heap-rs"
documentation = "http://tov.github.io/min-max-heap-rs/"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["heap", "priority-queue"]

[dependencies]

[dev-dependencies]
rand = "0.3"
